addons:
  postgresql: "9.2"
language: ruby
rvm:
  - 2.1
env:
  - DB=postgresql
  - POSTGRES_USERNAME=postgres
  - AWS_ACCESS_KEY_ID=foo
  - AWS_SECRET_ACCESS_KEY=bar
  - AWS_S3_BUCKET=foobar
before_script:
  - psql -c 'create database feedbin_test;' -U postgres
script:
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
